# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_msmarco-linker.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_msmarco-linker.ipynb 3
import os
os.environ['HIP_VISIBLE_DEVICES'] = '0,1,2,3,4,5'

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp, argparse

from xcai.basics import *
from xcai.models.PPP0XX import DBT009,DBT011

# %% ../nbs/01_msmarco-linker.ipynb 5
os.environ['WANDB_PROJECT'] = 'mogicX_00-msmarco-linker'

# %% ../nbs/01_msmarco-linker.ipynb 20
if __name__ == '__main__':
    output_dir = '/data/outputs/mogicX/01-msmarco-gpt-entity-linker-001'

    input_args = parse_args()

    if input_args.exact:
        config_file = '/data/datasets/msmarco/XC/configs/data_exact.json'
        config_key = 'data_exact'
    else:
        raise ValueError("`--exact` arguement is missing.")

    mname = 'sentence-transformers/msmarco-distilbert-dot-v5'

    pkl_dir = f'{input_args.pickle_dir}/mogicX'
    pkl_file = get_pkl_file(pkl_dir, 'msmarco_data_distilbert-base-uncased', input_args.use_sxc_sampler, 
                            input_args.exact, input_args.only_test)

    do_inference = input_args.do_train_inference or input_args.do_test_inference or input_args.save_train_prediction or input_args.save_test_prediction or input_args.save_representation

    os.makedirs(os.path.dirname(pkl_file), exist_ok=True)
    block = build_block(pkl_file, config_file, input_args.use_sxc_sampler, config_key, do_build=input_args.build_block, only_test=input_args.only_test, 
            n_slbl_samples=1, main_oversample=False)

    # entity information
    pkl_file = f'{pkl_dir}/wiki-entity-ngame_meta-info.joblib'
    if os.path.exists(pkl_file):
        meta_info_1 = joblib.load(pkl_file)
    else:
        fname = '/data/datasets/msmarco/XC/raw_data/wiki-entity_ngame.raw.csv'
        meta_info_1 = Info.from_txt(fname, max_sequence_length=32, padding=True, return_tensors='pt', info_column_names=["identifier", "input_text"],
                tokenization_column="input_text", use_tokenizer=True, tokenizer=mname)
        joblib.dump(meta_info_1, pkl_file)

    pkl_file = f'{pkl_dir}/wiki-entity-ngame-active_meta-info.joblib'
    if os.path.exists(pkl_file):
        meta_info_2 = joblib.load(pkl_file)
    else:
        fname = '/data/datasets/msmarco/XC/raw_data/wiki-entity_ngame_active.raw.csv'
        meta_info_2 = Info.from_txt(fname, max_sequence_length=32, padding=True, return_tensors='pt', info_column_names=["identifier", "input_text"],
                tokenization_column="input_text", use_tokenizer=True, tokenizer=mname)
        joblib.dump(meta_info_2, pkl_file)

    linker_dset = SXCDataset(SMainXCDataset(data_info=meta_info_1, lbl_info=meta_info_2))
    # entity information

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=800,
        per_device_eval_batch_size=800,
        representation_num_beams=5, # 200,
        representation_accumulation_steps=1,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=300,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        adam_epsilon=1e-6,
        warmup_steps=100,
        weight_decay=0.01,
        learning_rate=2e-6,
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,
    
        metric_for_best_model='P@1',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=False,
        use_cpu_for_clustering=True,
    )

    def model_fn(mname, bsz):
        model = DBT009.from_pretrained(mname, bsz=bsz, tn_targ=5000, margin=0.3, tau=0.1, n_negatives=10, 
                                       apply_softmax=True, use_encoder_parallel=True)
        return model
    
    def init_fn(model): 
        model.init_dr_head()

    bsz = max(args.per_device_train_batch_size, args.per_device_eval_batch_size)*torch.cuda.device_count()

    model = load_model(args.output_dir, model_fn, {"mname": mname, "bsz": bsz}, init_fn, do_inference=do_inference, 
            use_pretrained=input_args.use_pretrained)
    
    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=linker_dset,
        eval_dataset=linker_dset,
        data_collator=block.collator,
    )
    
    trn_repr, tst_repr, lbl_repr, trn_pred, tst_pred = main(learn, input_args, n_lbl=linker_dset.data.n_lbl, eval_k=1, train_k=1)

    assert len(tst_pred.indices) == tst_pred.shape[0]
    entity_map = dict({p:q for p,q in enumerate(tst_pred.indices)})

    fname = 'wiki-entity-ngame_2_wiki-entity-ngame-active_from_linker.joblib'
    pkl_dir = '/data/datasets/msmarco/XC/raw_data/maps/'
    os.makedirs(os.path.dirname(pkl_dir), exist_ok=True)

    joblib.dump(entity_map, f'{pkl_dir}/{fname}')
