# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2,3'

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp

from transformers import DistilBertConfig

from xcai.basics import *
from xcai.models.PPP0XX import DBT023, DBTConfig


# start ablation

import torch.nn.functional as F

from typing import Optional
from fastcore.utils import *
from fastcore.meta import *

from xcai.models.PPP0XX import DBT023Encoder, Pooling

@patch
def forward(
    self:DBT023Encoder, 
    input_ids:Optional[torch.Tensor]=None, 
    attention_mask:Optional[torch.Tensor]=None,
    **kwargs
):
    o = self.distilbert(
        input_ids=input_ids,
        attention_mask=attention_mask,
        **kwargs
    )
    rep = Pooling.mean_pooling(o[0], attention_mask)
    return o, F.normalize(rep, dim=1) if self.config.normalize else rep

# end ablation


# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ['WANDB_PROJECT'] = 'mogicX_00-msmarco'

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    output_dir = '/home/sasokan/suchith/outputs/mogicX/37_training-msmarco-distilbert-from-scratch-012'

    input_args = parse_args()
    input_args.use_sxc_sampler = True

    if input_args.exact:
        config_file = '/data/datasets/beir/msmarco/XC/configs/data_lbl_ce-negatives-topk-05_exact.json'
        config_key = 'data_lbl_ce-negatives-topk-05_exact'
    else:
        raise NotImplementedError('Create a configuration file for using all the labels.')
    
    mname = 'distilbert-base-uncased'

    pkl_file = get_pkl_file(input_args.pickle_dir, 'msmarco_data-lbl-ce-negatives-topk-05-exact_distilbert-base-uncased', input_args.use_sxc_sampler, 
                            input_args.exact, input_args.only_test)

    do_inference = input_args.do_train_inference or input_args.do_test_inference or input_args.save_train_prediction or input_args.save_test_prediction or input_args.save_representation

    os.makedirs(os.path.dirname(pkl_file), exist_ok=True)
    block = build_block(pkl_file, config_file, input_args.use_sxc_sampler, config_key, do_build=input_args.build_block, 
                        only_test=input_args.only_test, main_oversample=True, meta_oversample=True, return_scores=True, 
                        n_slbl_samples=1, n_sdata_meta_samples=1)

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=800,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=['plbl2data_idx', 'plbl2data_data2ptr'],
        search_normalize=False, 
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,
    
        metric_for_best_model='P@1',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    config = DBTConfig(normalize=False, use_layer_norm=False, use_encoder_parallel=True)

    def model_fn(mname):
        return DBT023.from_pretrained(mname, config=config) 
    
    metric = PrecReclMrr(block.test.dset.n_lbl, block.test.data_lbl_filterer, pk=10, rk=200, rep_pk=[1, 3, 5, 10], 
                         rep_rk=[10, 100, 200], mk=[5, 10, 20])

    model = load_model(args.output_dir, model_fn, {"mname": mname}, do_inference=do_inference, 
                       use_pretrained=input_args.use_pretrained)

    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=block.train.dset,
        eval_dataset=block.test.dset,
        data_collator=block.collator,
        compute_metrics=metric,
    )
    
    main(learn, input_args, n_lbl=block.test.dset.n_lbl)
    
