# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_msmarco-linker.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_msmarco-linker.ipynb 3
import os
os.environ['HIP_VISIBLE_DEVICES'] = '4,5'

import torch, json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp

from xcai.basics import *
from xcai.models.PPP0XX import DBT009

from xcai.sdata import SMainXCDataset

# %% ../nbs/01_msmarco-linker.ipynb 5
os.environ['WANDB_PROJECT'] = 'mogicX_01-nq-linker'

# %% ../nbs/01_msmarco-linker.ipynb 20
if __name__ == '__main__':
    output_dir = '/home/aiscuser/scratch1/outputs/mogicX/40-nq-ngame-category-linker-001'

    config_file = '/data/datasets/nq/XC/configs/data_kaggle_categories.json'
    config_key = 'data_kaggle'
    
    mname = 'sentence-transformers/msmarco-distilbert-cos-v5'

    input_args = parse_args()

    pkl_file = get_pkl_file(input_args.pickle_dir, 'nq_data-kaggle-category_distilbert-base-uncased', 
            input_args.use_sxc_sampler, input_args.exact, input_args.only_test)

    do_inference = input_args.do_train_inference or input_args.do_test_inference or input_args.save_train_prediction or input_args.save_test_prediction or input_args.save_representation

    os.makedirs(os.path.dirname(pkl_file), exist_ok=True)
    block = build_block(pkl_file, config_file, input_args.use_sxc_sampler, config_key, do_build=input_args.build_block)

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=800,
        per_device_eval_batch_size=800,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=300,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        adam_epsilon=1e-6,                                                                                                                                          warmup_steps=100,
        weight_decay=0.01,
        learning_rate=2e-4,
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,
    
        metric_for_best_model='P@1',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    def model_fn(mname):
        model = DBT009.from_pretrained(mname, margin=0.3, tau=0.1, n_negatives=10, apply_softmax=True, use_encoder_parallel=True)
        return model
    
    def init_fn(model): 
        model.init_dr_head()

    linker_block = block.linker_dset('cat_meta')

    # linker_block = block.linker_dset('ent_meta', remove_empty=False)
    # linker_block.train.dset = linker_block.inference_dset(linker_block.train.dset.data.data_info, linker_block.train.dset.data.data_lbl, 
    #                                                       linker_block.train.dset.data.lbl_info, linker_block.train.dset.data.data_lbl_filterer)
    # linker_block.test.dset = linker_block.inference_dset(linker_block.test.dset.data.data_info, linker_block.test.dset.data.data_lbl, 
    #                                                      linker_block.test.dset.data.lbl_info, linker_block.test.dset.data.data_lbl_filterer)

    metric = PrecReclMrr(linker_block.n_lbl, linker_block.test.data_lbl_filterer, prop=linker_block.train.dset.data.data_lbl,
                         pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200], mk=[5, 10, 20])

    model = load_model(args.output_dir, model_fn, {"mname": mname}, init_fn, do_inference=do_inference, use_pretrained=input_args.use_pretrained)
    
    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=linker_block.train.dset,
        eval_dataset=linker_block.test.dset,
        data_collator=linker_block.collator,
        compute_metrics=metric,
    )

    def load_info(fname):
        if os.path.exists(fname):
            info =  Info.from_txt(fname, max_sequence_length=32, info_column_names=['identifier', 'input_text'], use_tokenizer=True, 
                    tokenizer=mname, tokenization_column='input_text', padding=True, return_tensors='pt')
            return SMainXCDataset(data_info=info)

    train_dataset = load_info(f'/data/datasets/{input_args.dataset}/XC/raw_data/train.raw.txt') 
    eval_dataset = load_info(f'/data/datasets/{input_args.dataset}/XC/raw_data/test.raw.txt')

    input_args.prediction_suffix = input_args.dataset

    main(learn, input_args, n_lbl=linker_block.n_lbl, eval_dataset=eval_dataset, train_dataset=train_dataset, eval_k=10, train_k=10)
    
