# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/42_entity-conflation.ipynb.

# %% auto 0
__all__ = ['show_conflated_labels', 'load_data', 'Filter', 'get_one_hop', 'get_components', 'get_valid_components',
           'get_conflated_info', 'get_id_to_cluster_idx_mapping', 'get_conflated_matrix', 'get_conflated_path',
           'save_conflated_data', 'main', 'parse_args']

# %% ../nbs/42_entity-conflation.ipynb 2
import scipy.sparse as sp, numpy as np, argparse, os
from tqdm.auto import tqdm
from termcolor import colored, COLORS
from scipy.sparse.csgraph import connected_components
from typing import List, Optional, Dict, Set

from sugar.core import load_raw_file, save_raw_file
from xclib.utils.sparse import retain_topk

# %% ../nbs/42_entity-conflation.ipynb 5
def show_conflated_labels(idxs:List, components:Dict, lbl_ids2txt:Dict, fname:Optional[str]=None):
    file = fname if fname is None else open(fname, 'w')
    for i, idx in enumerate(idxs):
        txt = " || ".join([lbl_ids2txt[o] for o in components[idx]])
        if fname is None: print(f'{i+1:03d}. {txt}')
        else: file.write(f'{i+1:03d}. {txt}\n')
    if fname is not None: file.close()
        

# %% ../nbs/42_entity-conflation.ipynb 8
def load_data(pred_file:str, trn_file:str, tst_file:str, lbl_file:str,
              encoding:Optional[str]='utf-8'):
    pred_lbl, trn_lbl, tst_lbl = sp.load_npz(pred_file), sp.load_npz(trn_file), sp.load_npz(tst_file)
    lbl_ids, lbl_txt = load_raw_file(lbl_file, encoding=encoding)
    return pred_lbl, trn_lbl, tst_lbl, (lbl_ids, lbl_txt)
    

# %% ../nbs/42_entity-conflation.ipynb 13
class Filter:

    @staticmethod
    def by_length(components:Dict, min_thresh:Optional[int]=1, max_thresh:Optional[int]=100):
        cluster_len = np.array([len(components[idx]) for idx in sorted(components)])
        mask = np.logical_and(np.where(cluster_len >= min_thresh, 1, 0), np.where(cluster_len <= max_thresh, 1, 0))
        return set(np.where(mask)[0])

    @staticmethod
    def topk(data_lbl:sp.csr_matrix, k:Optional[int]=3):
        return retain_topk(data_lbl, k=k)

    @staticmethod
    def threshold(data_lbl:sp.csr_matrix, t:int):
        idx = np.where(data_lbl.data < t)[0]
        data_lbl.data[idx] = 0
        data_lbl.eliminate_zeros()
        

# %% ../nbs/42_entity-conflation.ipynb 15
def get_one_hop(data_lbl:sp.csr_matrix, batch_size:Optional[int]=1000):
    lbl_data = data_lbl.T.tocsr()
    lbl_lbl = [lbl_data[i:i+batch_size]@data_lbl for i in tqdm(range(0, lbl_data.shape[0], batch_size))]
    return sp.vstack(lbl_lbl)
    

# %% ../nbs/42_entity-conflation.ipynb 17
def get_components(data_lbl:sp.csr_matrix, lbl_ids:List, batch_size:Optional[int]=1000):
    lbl_lbl = get_one_hop(data_lbl, batch_size)
    
    n_comp, clusters = connected_components(lbl_lbl, directed=False, return_labels=True)
    components = {}
    for idx,ids in zip(clusters, lbl_ids):
        components.setdefault(idx, []).append(ids)
    return components
    

# %% ../nbs/42_entity-conflation.ipynb 23
def get_valid_components(components:Dict, valid_cluster_idxs:Set):
    valid_components, lbl_ids2cluster = dict(), dict()

    curr_cluster_idx = 0
    for idx, cluster in components.items():
        if idx in valid_cluster_idxs:
            valid_components[curr_cluster_idx] = cluster
            for o in cluster: lbl_ids2cluster[o] = curr_cluster_idx
            curr_cluster_idx += 1
        else:
            for o in cluster:
                valid_components[curr_cluster_idx] = [o]
                lbl_ids2cluster[o] = curr_cluster_idx
                curr_cluster_idx += 1
                
    return valid_components, lbl_ids2cluster
    

# %% ../nbs/42_entity-conflation.ipynb 24
def get_conflated_info(components:Dict, lbl_ids2txt:Dict):
    return [" || ".join([lbl_ids2txt[o] for o in components[i]]) for i in sorted(components)]
        

# %% ../nbs/42_entity-conflation.ipynb 25
def get_id_to_cluster_idx_mapping(lbl_ids2cluster_map:Dict, lbl_ids:List):
    return np.array([lbl_ids2cluster_map[o] for o in lbl_ids])
    

# %% ../nbs/42_entity-conflation.ipynb 26
def get_conflated_matrix(data_lbl:sp.csr_matrix, lbl_ids2cluster:Dict):
    indices = [lbl_ids2cluster[idx] for idx in data_lbl.indices]
    data = len(indices) * [1]
    
    matrix = sp.csr_matrix((data, indices, data_lbl.indptr), dtype=np.float32)
    matrix.sum_duplicates()
    return matrix
    

# %% ../nbs/42_entity-conflation.ipynb 32
def get_conflated_path(fname):
    file_dir = os.path.dirname(fname)
    file_name, file_type = os.path.basename(fname).split('.', maxsplit=1)
    return f'{file_dir}/{file_name}_conflated.{file_type}'
    

# %% ../nbs/42_entity-conflation.ipynb 33
def save_conflated_data(lbl_txt:List, lbl_file:str, trn_lbl:sp.csr_matrix, trn_file:str, 
                        tst_lbl:sp.csr_matrix, tst_file:str):
    lbl_file = get_conflated_path(lbl_file)
    trn_file = get_conflated_path(trn_file)
    tst_file = get_conflated_path(tst_file)

    save_raw_file(lbl_file, range(len(lbl_txt)), lbl_txt)
    sp.save_npz(trn_file, trn_lbl)
    sp.save_npz(tst_file, tst_lbl)
    

# %% ../nbs/42_entity-conflation.ipynb 36
def main(pred_file:str, trn_file:str, tst_file:str, lbl_file:str, topk:Optional[int]=3,
         batch_size:Optional[int]=1024, min_thresh:Optional[int]=2, max_thresh:Optional[int]=100,
         encoding:Optional[str]='latin-1'):
    pred_lbl, trn_lbl, tst_lbl, (lbl_ids, lbl_txt) = load_data(pred_file, trn_file, tst_file, lbl_file, 
                                                               encoding=encoding)
    lbl_ids2txt = {k:v for k,v in zip(lbl_ids, lbl_txt)}

    data_lbl = Filter.topk(pred_lbl, k=topk)
    components = get_components(data_lbl, lbl_ids, batch_size)

    valid_cluster_idxs = Filter.by_length(components, min_thresh=min_thresh, max_thresh=max_thresh)
    
    valid_components, lbl_ids2cluster_map = get_valid_components(components, valid_cluster_idxs)
    conflated_lbl_txt = get_conflated_info(valid_components, lbl_ids2txt)
    lbl_ids2cluster = get_id_to_cluster_idx_mapping(lbl_ids2cluster_map, lbl_ids)

    conflated_trn_lbl = get_conflated_matrix(trn_lbl, lbl_ids2cluster)
    conflated_tst_lbl = get_conflated_matrix(tst_lbl, lbl_ids2cluster)

    save_conflated_data(conflated_lbl_txt, lbl_file, conflated_trn_lbl, trn_file, conflated_tst_lbl, tst_file)
    

# %% ../nbs/42_entity-conflation.ipynb 39
def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument('--pred_file', type=str, required=True)
    parser.add_argument('--lbl_file', type=str, required=True)
    parser.add_argument('--trn_file', type=str, required=True)
    parser.add_argument('--tst_file', type=str, required=True)

    parser.add_argument('--topk', type=int, default=3)
    parser.add_argument('--batch_size', type=int, default=1024)
    
    parser.add_argument('--min_thresh', type=int, default=2)
    parser.add_argument('--max_thresh', type=int, default=100)
    parser.add_argument('--encoding', type=str, default='latin-1')
    
    return parser.parse_args()
    

# %% ../nbs/42_entity-conflation.ipynb 40
if __name__ == '__main__':
    args = parse_args()
    
    main(args.pred_file, args.trn_file, args.tst_file, args.lbl_file, topk=args.topk, 
         batch_size=args.batch_size, min_thresh=args.min_thresh, max_thresh=args.max_thresh, 
         encoding=args.encoding)

