# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/44_ngame-gpt-conflated-entity-oracle-for-msmarco.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/44_ngame-gpt-conflated-entity-oracle-for-msmarco.ipynb 3
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp

from xcai.basics import *
from xcai.models.PPP0XX import DBT009

# %% ../nbs/44_ngame-gpt-conflated-entity-oracle-for-msmarco.ipynb 5
os.environ['WANDB_PROJECT'] = 'mogicX_00-msmarco-07'
