# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 2
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2,3,4,5'

import torch,json, torch.multiprocessing as mp, joblib, numpy as np, scipy.sparse as sp

from transformers import DistilBertConfig

from xcai.basics import *
from xcai.models.nvembed.NVM0XX import NVM009

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 4
os.environ['WANDB_PROJECT'] = 'mogicX_00-msmarco-08'

def get_instruction(fname, dset):
    with open(instruct_file) as file:
        instructions = json.load(file)
    return instructions[dset]

# %% ../nbs/37_training-msmarco-distilbert-from-scratch.ipynb 21
if __name__ == '__main__':
    output_dir = '/home/aiscuser/scratch1/outputs/mogicX/54_nvembed-for-msmarco-001'

    input_args = parse_args()

    input_args.use_sxc_sampler = True
    input_args.pickle_dir = "/home/aiscuser/scratch1/datasets/processed/"

    config_file = '/data/datasets/beir/msmarco/XC/configs/data.json'
    config_key, fname = get_config_key(config_file)
    mname = 'nvidia/NV-Embed-v2'

    pkl_file = get_pkl_file(input_args.pickle_dir, f'msmarco_{fname}_{mname.split("/")[1]}', input_args.use_sxc_sampler, 
                            input_args.exact, input_args.only_test)

    do_inference = check_inference_mode(input_args)

    instruct_file = "/home/aiscuser/scratch1/xcai/xcai/models/nvembed/instructions.json"
    data_prompt_func = lambda x: "Instruct: " + get_instruction(instruct_file, "MSMARCO")["query"] + f"\nQuery: {x}"

    os.makedirs(os.path.dirname(pkl_file), exist_ok=True)
    block = build_block(pkl_file, config_file, input_args.use_sxc_sampler, config_key, do_build=input_args.build_block, 
                        only_test=input_args.only_test, main_oversample=True, meta_oversample=True, return_scores=True, 
                        n_slbl_samples=1, n_sdata_meta_samples=1, tokenizer=mname, data_prompt_func=data_prompt_func, 
                        main_max_data_sequence_length=64, meta_max_sequence_length=64)

    args = XCLearningArguments(
        output_dir=output_dir,
        logging_first_step=True,
        per_device_train_batch_size=128,
        per_device_eval_batch_size=1,
        representation_num_beams=200,
        representation_accumulation_steps=10,
        save_strategy="steps",
        eval_strategy="steps",
        eval_steps=5000,
        save_steps=5000,
        save_total_limit=5,
        num_train_epochs=50,
        predict_with_representation=True,
        representation_search_type='BRUTEFORCE',
        search_normalize=False, 

        adam_epsilon=1e-6,
        warmup_steps=1000,
        weight_decay=0.01,
        learning_rate=6e-5,
        label_names=['plbl2data_idx', 'plbl2data_data2ptr'],
    
        group_by_cluster=True,
        num_clustering_warmup_epochs=10,
        num_cluster_update_epochs=5,
        num_cluster_size_update_epochs=25,
        clustering_type='EXPO',
        minimum_cluster_size=2,
        maximum_cluster_size=1600,
    
        metric_for_best_model='P@1',
        load_best_model_at_end=True,
        target_indices_key='plbl2data_idx',
        target_pointer_key='plbl2data_data2ptr',
    
        use_encoder_parallel=True,
        max_grad_norm=None,
        fp16=True,

        use_cpu_for_searching=True,
        use_cpu_for_clustering=True,
    )

    def model_fn(mname):
        model = NVM009.from_pretrained(mname, margin=0.3, tau=0.1, n_negatives=10, apply_softmax=True, use_encoder_parallel=True)
        return model

    def init_fn(model): 
        pass
    
    metric = PrecReclMrr(block.test.dset.n_lbl, block.test.data_lbl_filterer, pk=10, rk=200, rep_pk=[1, 3, 5, 10], 
                         rep_rk=[10, 100, 200], mk=[5, 10, 20])

    bsz = max(args.per_device_train_batch_size, args.per_device_eval_batch_size)*torch.cuda.device_count()

    model = load_model(args.output_dir, model_fn, {"mname": mname}, init_fn, do_inference=do_inference, use_pretrained=input_args.use_pretrained)
    
    learn = XCLearner(
        model=model,
        args=args,
        train_dataset=None if block.train is None else block.train.dset,
        eval_dataset=block.test.dset,
        data_collator=block.collator,
        compute_metrics=metric,
    )
    
    main(learn, input_args, n_lbl=block.test.dset.n_lbl, eval_k=10, train_k=10, save_teacher=True)
    
